/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(frame_info_to_pdu.h) */
/* BINDTOOL_HEADER_FILE_HASH(5a4a4360f1a352d2c3aa2a95a63edd5d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/frame_info_to_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <frame_info_to_pdu_pydoc.h>

void bind_frame_info_to_pdu(py::module &m) {

  using frame_info_to_pdu = ::gr::lora_sdr::frame_info_to_pdu;

  py::class_<frame_info_to_pdu, gr::block, gr::basic_block,
             std::shared_ptr<frame_info_to_pdu>>(m, "frame_info_to_pdu",
                                              D(frame_info_to_pdu))

      .def(py::init(&frame_info_to_pdu::make),
           D(frame_info_to_pdu, make))

      ;
}
