/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(pdu_to_whitening_msg.h) */
/* BINDTOOL_HEADER_FILE_HASH(e15ad60731b6785dda0e94928e25f31c) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/pdu_to_whitening_msg.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_to_whitening_msg_pydoc.h>

void bind_pdu_to_whitening_msg(py::module &m) {

  using pdu_to_whitening_msg = ::gr::lora_sdr::pdu_to_whitening_msg;

  py::class_<pdu_to_whitening_msg, gr::block, gr::basic_block,
             std::shared_ptr<pdu_to_whitening_msg>>(m, "pdu_to_whitening_msg",
                                              D(pdu_to_whitening_msg))

      .def(py::init(&pdu_to_whitening_msg::make),
           D(pdu_to_whitening_msg, make))

      ;
}
